[package]
name = "skap"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake3 = { version = "1.5.4", features = ["serde"] }
bytes = "1.8.0"
chacha20poly1305 = "0.10.1"
crystals-dilithium = "1.0.0"
lazy_static = "1.5.0"
pqc_kyber = { version = "0.7.1", features = ["kyber1024", "std"] }
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_with = "3.11.0"
sharks = "0.5.0"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4", "serde", "fast-rng"] }
warp = "0.3.7"
